Logical: anam_saType
Id: anam-satype
Title: "anam_saType"
Description: "A complex type representing anam_saType with various attributes."
* ^extension[http://hl7.org/fhir/tools/StructureDefinition/xml-namespace].valueUri = "urn:cz-mzcr:ns:dasta:ds4:ds_ip"

* sau_prac 0..1 string "Element sau_prac."
* sau_zajmy 0..1 string "Element sau_zajmy."
* sau_soc 0..1 string "Element sau_soc."
* sav_vzdel 0..1 string "Element sav_vzdel."
* sav_koment 0..1 string "Element sav_koment."
* sab_zpbydl_text 0..1 string "Element sab_zpbydl_text."
* sab_zpbydl_kod 0..1 str32 "Element sab_zpbydl_kod."
* sab_prizp_text 0..1 string "Element sab_prizp_text."
* sab_prizp_kod 0..* str32 "Element sab_prizp_kod."
* sab_bariery_text 0..1 string "Element sab_bariery_text."
* sab_bariery_kod 0..* str32 "Element sab_bariery_kod."
* sar_koment 0..1 string "Element sar_koment."
* sar_slozrod_text 0..1 string "Element sar_slozrod_text."
* sar_rodstav_text 0..1 string "Element sar_rodstav_text."
* sar_pocdet 0..1 str2 "Element sar_pocdet."
* sar_pocdetd 0..1 str2 "Element sar_pocdetd."
* sar_dite 0..* string "Element sar_dite."
* sar_pecezc 0..* string "Element sar_pecezc."
