Logical: anfType
Id: anftype
Title: "anfType"
Description: "A complex type representing anfType with various attributes."
* ^extension[http://hl7.org/fhir/tools/StructureDefinition/xml-namespace].valueUri = "urn:cz-mzcr:ns:dasta:ds4:ds_ip"

* anam_prob 0..* anam_probType "Element anam_prob."
* anam_zpi 0..* anam_zpiType "Element anam_zpi."
* anam_vyk 0..* anam_vykType "Element anam_vyk."
* anam_oc 0..* anam_ocType "Element anam_oc."
* anam_trf 0..1 anam_trfType "Element anam_trf."
* anam_gyn 0..1 anam_gynType "Element anam_gyn."
* anam_inf 0..* anam_infType "Element anam_inf."
* anam_infc 0..* anam_infcType "Element anam_infc."
* anam_rao 0..* anam_raoType "Element anam_rao."
* anam_sa 0..1 anam_saType "Element anam_sa."
* anam_aba 0..* anam_abaType "Element anam_aba."
* anam_abk 0..* anam_abkType "Element anam_abk."
* anam_abd 0..* anam_abdType "Element anam_abd."
* anam_abj 0..1 anam_abjType "Element anam_abj."
* garant_dat 0..1 garant_datType "Element garant_dat."
* autor 0..1 autorType "Element autor."
* dat_ab 0..1 dat_xxType "Element dat_ab."
* iid 0..1 iidType "Element iid."
* anAny 0..1 AnyType "Element anAny."
