Logical: ip
Id: ip
Title: "ip"
Description: "A element type representing ip with various attributes."
* ^extension[http://hl7.org/fhir/tools/StructureDefinition/xml-namespace].valueUri = "urn:cz-mzcr:ns:dasta:ds4:ds_ip"

* rodcis 0..1 rodcisType "Element rodcis."
* rip 0..1 str10 "Element rip."
* id_card 0..1 id_cardType "Element id_card."
* passport 0..1 passportType "Element passport."
* jmeno 0..1 str40 "Element jmeno."
* prijmeni 0..1 str40 "Element prijmeni."
* titul_pred 0..1 str35 "Element titul_pred."
* titul_za 0..1 str35 "Element titul_za."
* dat_dn 0..1 dat_xxType "Element dat_dn."
* misto_nar 0..1 str40 "Element misto_nar."
* stat_pris 0..1 str3 "Element stat_pris."
* dat_de 0..1 dat_xxType "Element dat_de."
* sex 0..1 sexType "Element sex."
* sex_klin 0..1 sexType "Element sex_klin."
* rod_prijm 0..1 str40 "Element rod_prijm."
* jine_idu 0..1 str70 "Element jine_idu."
* typ_sdel 0..1 Element "Element typ_sdel."
  * txt 1..1 string "Text inside restriction element."
    * ^representation = #xmlText
    * ^code = #ALL
    * ^code = #PS
    * ^code = #KU
* duvernost 0..1 Element "Element duvernost."
  * txt 1..1 string "Text inside restriction element."
    * ^representation = #xmlText
* jazyk 0..* jazykType "Element jazyk."
* ipi_o 0..1 ipiType "Element ipi_o."
* ipi_v 0..1 ipiType "Element ipi_v."
* a 0..1 aType "Element a."
* povolani 0..* povolaniType "Element povolani."
* h 0..* hType "Element h."
* fyznal 0..* fyznalType "Element fyznal."
* grav 0..1 gravType "Element grav."
* pv_pac 0..1 pv_pacType "Element pv_pac."
* p 0..* pType "Element p."
* n 0..1 nType "Element n."
* u 0..1 uType "Element u."
* an 0..1 anType "Element an."
* anf 0..1 anfType "Element anf."
* oc 0..1 ocType "Element oc."
* dg 0..1 dgType "Element dg."
* le 0..1 leType "Element le."
* lek 0..1 lekType "Element lek."
* chv 0..* chvType "Element chv."
* fzs 0..1 fzsType "Element fzs."
* ld 0..1 ldType "Element ld."
* fs 0..1 fsType "Element fs."
* pn 0..1 pnType "Element pn."
* ts 0..1 tsType "Element ts."
* tps 0..1 tpsType "Element tps."
* ku 0..1 Element "Element ku."
  * ku_p 0..* ku_pType "Element ku_p."
  * ku_z 0..* ku_zType "Element ku_z."
  * ku_o 0..* ku_oType "Element ku_o."
  * ku_a 0..* ku_aType "Element ku_a."
  * ku_r 0..* ku_rType "Element ku_r."
  * kuAny 0..1 AnyType "Element kuAny."
* ipAny 0..1 AnyType "Element ipAny."
* id_pac 1..1 string "Required id_pac attribute."
  * ^representation = #xmlAttr
* typ_id_pac 0..1 string "Optional typ_id_pac attribute."
  * ^representation = #xmlAttr
  * ^defaultValueString = "0"
  * ^code = #0
  * ^code = #1
