Logical: ku_z_patsumdatType
Id: ku-z-patsumdattype
Title: "ku_z_patsumdatType"
Description: "A complex type representing ku_z_patsumdatType with various attributes."
* ^extension[http://hl7.org/fhir/tools/StructureDefinition/xml-namespace].valueUri = "urn:cz-mzcr:ns:dasta:ds4:ds_ip"

* jazyk 0..* jazykType "Element jazyk."
* povolani 0..* povolaniType "Element povolani."
* h 0..* hType "Element h."
* fyznal 0..* fyznalType "Element fyznal."
* grav 0..1 gravType "Element grav."
* pv_pac 0..1 pv_pacType "Element pv_pac."
* u 0..1 uType "Element u."
* an 0..1 anType "Element an."
* anf 0..1 anfType "Element anf."
* oc 0..1 ocType "Element oc."
* dg 0..1 dgType "Element dg."
* le 0..1 leType "Element le."
* chv 0..* chvType "Element chv."
* fzs 0..1 fzsType "Element fzs."
* ld 0..1 ldType "Element ld."
* fs 0..1 fsType "Element fs."
* zdroj_sw 0..1 zdroj_isType "Element zdroj_sw."
  * ^extension[http://hl7.org/fhir/tools/StructureDefinition/xml-namespace].valueUri = "urn:cz-mzcr:ns:dasta:ds4:ds_dasta"
